SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


CREATE USER '{MYSQL_USER}'@'{MYSQL_HOST}' IDENTIFIED BY '{MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '{MYSQL_USER}'@'{MYSQL_HOST}';
FLUSH PRIVILEGES;
